export const DOCS_PAGES = [
  {
    slug: "getting-started",
    title: "Getting Started",
    description: "Installation, setup, and your first session",
    category: "Getting Started",
    file: "getting-started-guide.md",
    icon: "Rocket",
  },
  {
    slug: "chat-tasks",
    title: "AI Chat & Tasks",
    description: "Master the conversation system",
    category: "Core Features",
    file: "chat-tasks-guide.md",
    icon: "MessageSquare",
  },
  {
    slug: "project-management",
    title: "Project Board, Wiki & Visual Editor",
    description: "Task management, documentation, and design tools",
    category: "Core Features",
    file: "user-guide.md",
    icon: "ClipboardList",
  },
  {
    slug: "skills",
    title: "Skills",
    description: "AI skill modules for specialized tasks",
    category: "Skills",
    file: "skills-guide.md",
    icon: "Sparkles",
  },
  {
    slug: "custom-skills",
    title: "Creating Custom Skills",
    description: "Build your own domain-specific AI skills",
    category: "Skills",
    file: "custom-skills-guide.md",
    icon: "Wrench",
  },
  {
    slug: "mcp-connectors",
    title: "MCP Connectors",
    description: "Connect to external tools and services",
    category: "Integrations",
    file: "mcp-connectors-guide.md",
    icon: "Plug",
  },
  {
    slug: "settings",
    title: "Settings & Configuration",
    description: "API providers, sandbox, credentials, and more",
    category: "Configuration",
    file: "settings-guide.md",
    icon: "Settings",
  },
  {
    slug: "learning-creative-hubs",
    title: "Learning Hub & Creative Hub",
    description: "AI-powered learning and creative content generation",
    category: "Hubs",
    file: "learning-creative-hubs-guide.md",
    icon: "GraduationCap",
  },
  {
    slug: "unified-platform",
    title: "Unified AI Platform",
    description: "How all features work together with shared context",
    category: "Advanced",
    file: "unified-platform-guide.md",
    icon: "Layers",
  },
] as const;

export type DocPage = (typeof DOCS_PAGES)[number];
